### ISSUE TITLE
Add Licensing Information

### ISSUE THREAD

**Issue by SableRaf** [diyaayay/processing4.3JRE#1]
It is important to include licensing information in this repository. This ensures that users are informed about the licensing terms of the Processing components included in the `.zip` file.

The Processing core library itself is licensed under the LGPL but some of its [third-party dependencies](https://github.com/benfry/processing4/blob/main/LICENSE.md#third-party-open-source-software-used) are under other licenses.

For detailed license information, please refer to https://github.com/processing/processing4/blob/main/LICENSE.md

**Comment by diyaayay** [comment]
Hi @SableRaf. I have included the license now, I have decided [to go with](https://github.com/diyaayay/processing4.3JRE#GPL-3.0-1-ov-file) `GPL-3.0`.
Also, now I have moved the `.zip` file to the release section.

**Comment by SableRaf** [comment]
Great! Thanks @diyaayay 

I'm not a licensing expert or a lawyer, but it looks like GPL v3 allows including LGPL 2.1 code so we should be good:

https://www.gnu.org/licenses/gpl-faq.en.html#compat-matrix-footnote-7

**Comment by diyaayay** [comment]
Right, `GPL v3` allows including `LGPL 2.1` code. Initially, I planned to go with `GPLv2` but it turns out that it does not permit combinations with `LGPL v3.` So I think `GPL v3` is good to go.
